repos:
-   repo: https://github.com/Tribler/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
        types: [file, python]

-   repo: https://github.com/Tribler/isort
    rev: 4.3.21-3-tribler
    hooks:
    - id: isort
      types: [file, python]

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      files: |
          (?x)(
          ^src/tribler-gui/|
          ^src/tribler-core/tribler_core/modules/metadata_store/|
          ^src/tribler-common
          )
      types: [file, python]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -  id: flake8
       types: [file, python]
